apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mycluster-deployment
  labels:
    app: mycluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mycluster
  template:
    metadata:
      labels:
        app: mycluster
    spec:
      containers:
      - name: mycluster
        image: bernardolins/mycluster:0.0.5
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REPLACE_OS_VARS
          value: "true"
        ports:
        - containerPort: 4000

---

kind: Service
apiVersion: v1
metadata:
  name: mycluster-service
  labels:
    app: mycluster
spec:
  ports:
    - protocol: TCP
      name: mycluster
      port: 4000
      targetPort: 4000
  selector:
    app: mycluster
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: mycluster-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
